name: Build and Test

on: [push, pull_request]

jobs:
  release:
    strategy:
      matrix:
        os: [macos-10.15, macos-latest, ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}.build

      - name: Configure CMake
        run: cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=Release
        working-directory: ${{github.workspace}}.build

      - name: Build
        run: cmake --build .
        working-directory: ${{github.workspace}}.build

      - name: Test
        run: ctest
        working-directory: ${{github.workspace}}.build

  debug:
    strategy:
      matrix:
        os: [macos-10.15, macos-latest, ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}.build

      - name: Configure CMake
        run: cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=Debug -DDEBUG_PARSING=1
        working-directory: ${{github.workspace}}.build

      - name: Build
        run: cmake --build .
        working-directory: ${{github.workspace}}.build

      - name: Test
        run: ctest
        working-directory: ${{github.workspace}}.build

  debug-old-gcc:
    strategy:
      matrix:
        gcc-version: [4.8]
        os: [ubuntu-16.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install gcc-${{ matrix.gcc-version }}
        run: sudo apt-get install -y gcc-${{ matrix.gcc-version }} g++-${{ matrix.gcc-version }}
      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}.build

      - name: Configure CMake
        run: cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=Debug -DDEBUG_PARSING=1
        working-directory: ${{github.workspace}}.build
        env:
          CC: gcc-${{ matrix.gcc-version }}
          CXX: g++-${{ matrix.gcc-version }}

      - name: Build
        run: cmake --build .
        working-directory: ${{github.workspace}}.build

      - name: Test
        run: ctest
        working-directory: ${{github.workspace}}.build
